### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by abhijeetasawant** [stricaud/faup#121]
cmake fails with error:

-- Configuring done
CMake Error at src/tests/CMakeLists.txt:32 (add_executable):
  Cannot find source file:

    issue120.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc

CMake Error at src/tests/CMakeLists.txt:32 (add_executable):
  No SOURCES given to target: issue120

**Comment by ryangar88** [comment]
I get same issue :(

**Comment by github-germ** [comment]
same issue here also

**Comment by github-germ** [comment]
note: this works if we clone v1.5

**Comment by github-germ** [comment]
well, using v1.5 broke things downstream in my build. so my temp fix for now is:
```
git clone --depth 1 https://github.com/stricaud/faup.git /tmp/faup
cd /tmp/faup/src/tests || exit; sed -i '/issue120/d' ./CMakeLists.txt
```

**Comment by syloktools** [comment]
> well, using v1.5 broke things downstream in my build. so my temp fix for now is:
> 
> ```
> git clone --depth 1 https://github.com/stricaud/faup.git /tmp/faup
> cd /tmp/faup/src/tests || exit; sed -i '/issue120/d' ./CMakeLists.txt
> ```

I have the same issue. thanks for this workaround :)

**Comment by cristianamusca** [comment]
same issue. moved HEAD back with 2 commits to work

**Comment by stricaud** [comment]
My bad! I pushed the missing test :( sorry for that
