### ISSUE TITLE
Downloading the list fails

### ISSUE THREAD

**Issue by Bu11etmagnet** [stricaud/faup#54]
GET http://io.libio.so/effective_tld_names.dat HTTP/1.0

HTTP/1.1 404 Not Found
Date: Fri, 29 Aug 2014 08:57:16 GMT
Server: Apache/2.4.10 (Debian)
Keep-Alive: timeout=5, max=100
Content-Type: text/html; charset=iso-8859-1
Content-Length: 304
Accept-Ranges: none
Connection: close

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /effective_tld_names.dat was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at ns3362673.ovh.net Port 80</address>
</body></html>

This is not how HTTP works. If you connect directly to port 80 on the server, then the request should be

GET /effective_tld_names.dat HTTP/1.0

However, io.libio.so seems to be (mis)configurede to return 404 if the Host: header is not present.

**Comment by stricaud** [comment]
I fixed a lot of things recently. This works here:

$ ./src/tools/faup -u
$ ls -l ~/.faup/mozilla.tlds 
-rw-rw-r--. 1 sebastien sebastien 130119 May 14 23:58 /home/sebastien/.faup/mozilla.tlds
$ date
Sat May 14 23:58:48 PDT 2016

Please re-open if you have an issue on your side. Thanks!

**Comment by Bu11etmagnet** [comment]
Works now, thanks.
