### ISSUE TITLE
Path parsing

### ISSUE THREAD

**Issue by clickstefan** [stricaud/faup#58]
the path includes the "?" character

e.g.:
http://cache.google.com/?q=http://www.google.com/path/to/search.html?q=test&loc=ro%20Romania
scheme:             http
subDomain:          cache
topDomain:          google.com
domain:             cache.google.com
tld:                com
path:               /?q=http://www.google.com/path/to/search.html
query:              ?q=test&loc=ro%20Romania

expected: 
Path: /
Query: ?q=http://www.google.com/path/to/search.html?q=test&loc=ro%20Romania

see http://www.freeformatter.com/url-parser-query-string-splitter.html

**Comment by stricaud** [comment]
This has been fixed in an earlier commit:
$ ./src/tools/faup -o json "http://cache.google.com/?q=http://www.google.com/path/to/search.html?q=test&loc=ro%20Romania"
{
	"scheme": "http",
	"credential": "",
	"subdomain": "cache",
	"domain": "google.com",
	"domain_without_tld": "google",
	"host": "cache.google.com",
	"tld": "com",
	"port": "",
	"resource_path": "/?q=http://www.google.com/path/to/search.html",
	"query_string": "?q=test&loc=ro%20Romania",
	"fragment": "",
	"url_type": "mozilla_tld"
}

Thank you very much for the reporting. Adding a test for this one.
