### ISSUE TITLE
Is it possible to have a flag set when the tld doesn't match the list of tlds from Mozilla ?

### ISSUE THREAD

**Issue by clickstefan** [stricaud/faup#63]
It would help to invalidate bad links

**Comment by stricaud** [comment]
Could you please open a new issue the the IDN specifically so we can have a conversation over there? I have no problem handling non-ascii domains. What do we want to archive here?

I keep this ticket open to solve the issue you mentioned. I will add a new field that also tells you if this was an IP address.

Thanks!
