### ISSUE TITLE
supporting idn

### ISSUE THREAD

**Issue by stricaud** [stricaud/faup#64]
Taken from clickstefan in issue #63:

Also another idea is to have `idn` integrated, I use it to normalize domains, as it helps with :
- adding domains to a database, it's nice to not have duplicates and ascii is more compatible with most net tools.
- helps in validating domains (after idn you can check for non [A-Z0-9.-] characters in the domain and invalidate)

The [chrome url library](https://chromium.googlesource.com/chromium/src.git/+/41.0.2252.2/url/) does a good job at normalization, but it's stuffed with too many options and dependencies.

**Comment by clickstefan** [comment]
hmm, I forgot you don't actually modify the input so it's probably best to keep it outside the faup lib, could be implemented in the command line tool if needed 

1. input
2. idn
3. faup processing

eg: domain.РФ   gets processed as    domain.xn--p1ai

ref:  [idn tlds](https://www.mozilla.org/en-US/about/governance/policies/security-group/tld-idn/#country-code)

**Comment by stricaud** [comment]
I agree, I do not want to alter the input within the library. However having a lua support using the lua modules would make sense. I am closing this ticket since this is more a nice to have than an issue with faup.

If there is enough people asking for that feature though, I will of course reconsider.

Thanks! Bringing this discussion is always useful.
