### ISSUE TITLE
Python packaging

### ISSUE THREAD

**Issue by 2xyo** [stricaud/faup#66]
Where is faup on [pypy](https://pypi.python.org/pypi/faup) ;-) ?

**Comment by Rafiot** [comment]
Hey, is there a change to do it? I'm not sure how it works to bundle the lib and the python API in a pypi package, but if someone know, that would be really great!

**Comment by stricaud** [comment]
I must do it, let me write a post-it on my desk to make sure I will do it. I agree it will be much better!

**Comment by Rafiot** [comment]
\o/ thank you very much! And I'm curious to see how that works :)

**Comment by stricaud** [comment]
alright, finally, after all these years! \o/

https://pypi.org/project/pyfaup/

**Comment by Rafiot** [comment]
Wohooooo \o/ thank you soo much!
