### ISSUE TITLE
Incorrect TLD type when piping multiple lines to faup

### ISSUE THREAD

**Issue by jksecurity** [stricaud/faup#69]
Hello,

I came across an interesting bug in faup. The TLD type (mozilla_tld, no_tld, unknown_tld) seems to be incorrect when I pipe a list of domains to faup to parse.

If you create the following input file:

localhost
localhost
localhost

faup will correctly tag all lines as no_tld

If you create the following input file:

localhost.com
localhost
localhost

faup will incorrectly tag the last two lines as mozilla_tld. It seems faup takes the value from the line above. If you change the first line to localhost.bla, all three lines will be tagged as unknown_tld.

**Comment by stricaud** [comment]
Thank you for the report. I will have a look.

**Comment by jksecurity** [comment]
Cool man, we love your tool nonetheless. We integrated it with our logstash environment to split out domain names for proxy and dns logs in real time, for close to 200 million events per day :)
