### ISSUE TITLE
IPv6 Loopback address parse issue

### ISSUE THREAD

**Issue by jksecurity** [stricaud/faup#70]
Hi,

I've come across a small issue with faup when trying to parse the IPv6 loopback address. Some of my servers are performing faulty DNS requests for "::1" which is causing issues when parsing the logs with faup.

I get the following result on my RHEL6 server:

$ echo "::1" | faup
Error: field(domain) with size(30168544) is greater than the maximum default FAUP URL MAXLEN (8192). Cannot process the given url (::1).
Error: field(domain_without_tld) with size(30168544) is greater than the maximum default FAUP URL MAXLEN (8192). Cannot process the given url (::1).
Error: field(host) with size(30168544) is greater than the maximum default FAUP URL MAXLEN (8192). Cannot process the given url (::1).
,,,,,,,1,,,,no_tld

I also noticed that on my CentOS VM it actually returns jibberish, most likely it pops some data off the stack and drops it on the command line.

P.S. I am not sure how it should return this. Perhaps the host in this case should still be ::1 and the domains should be empty?

**Comment by stricaud** [comment]
Thank you very much for this report... and it is now working with the latest version, this is what it gives in that case:
{
	"scheme": "",
	"credential": "",
	"subdomain": "",
	"domain": "::1",
	"domain_without_tld": "::1",
	"host": "::1",
	"tld": "",
	"port": "",
	"resource_path": "",
	"query_string": "",
	"fragment": "",
	"url_type": "ipv6"
}

**Comment by jksecurity** [comment]
Thx!
