### ISSUE TITLE
tld list not up to date

### ISSUE THREAD

**Issue by chervaliery** [stricaud/faup#71]
You change :
https://publicsuffix.org/list/effective_tld_names.dat
to : 
http://io.libio.so/effective_tld_names.dat
to avoid handle SSL, but the list on your own server only contains 6707 tld while the other list has 7796 ones.

Is it possible to update it ? 
Thanks

**Comment by stricaud** [comment]
Yes. Will see how I can have lightweight code to do this. Thanks!

**Comment by stricaud** [comment]
Sorry I did not replied earlier, but this has been fixed and now uses the publicsuffic.org list and curl to download that file. This is fixed.
