### ISSUE TITLE
empty lines in stdin are completely skipped

### ISSUE THREAD

**Issue by jksecurity** [stricaud/faup#73]
Hello,

If you create a file that has empty lines and pipe that to faup, the output will only contain the non-empty items. The problem is that the output has a different amount of lines compared to the input.

My current usage of faup is something like this:

paste input_file <(cat input_file | cut -f 1 | faup) > output_file

Basically, I want to add additional columns to input_file based on the parsing done by faup. The unix paste command simply pastes line by line, thus the lack of the empty entries in the faup output causes misalignment.

For this usage, an empty output like ",,,,,,,,,no_tld" would be better, but I can image this would not suite everyone. Perhaps a command line switch would be necessary?

**Comment by stricaud** [comment]
The command line switch could be a good one. Let me see what I can do. Thanks for reporting this.

**Comment by stricaud** [comment]
Thank you for your feedback. I created the -e switch to do what you want:

```
$ cat myurls.txt 
foo

bar
$ faup myurls.txt 
,,,foo,foo,foo,,,,,,no_tld
,,,bar,bar,bar,,,,,,no_tld
$ faup -e myurls.txt 
,,,foo,foo,foo,,,,,,no_tld
,,,,,,,,,,,no_tld
,,,bar,bar,bar,,,,,,no_tld
,,,,,,,,,,,no_tld

```

**Comment by jksecurity** [comment]
Thanks a lot!
