### ISSUE TITLE
Buffer overrun in tld.c

### ISSUE THREAD

**Issue by jdiner** [stricaud/faup#74]
There is a buffer overrun bug in tld.c, lines 96 and 97:

	while ( (n=recv(sockfd, recvbuf, MAX_RECVBUF, 0)) > 0) {
		recvbuf[n] = '\0';

If n==MAX_RECVBUF then the assignment of a null-terminator will be one byte past the end of recvbuf.  This consistently causes a segfault in my process that links against the static build of libfaup.  The buffer overrun can be easily fixed reducing the max read length by 1 byte:

	while ( (n=recv(sockfd, recvbuf, MAX_RECVBUF - 1, 0)) > 0) {
		recvbuf[n] = '\0';

**Comment by stricaud** [comment]
Thanks for reporting this. Fixed in the main tree.
