### ISSUE TITLE
Fragment parsed incorrectly if path is implicit

### ISSUE THREAD

**Issue by jdiner** [stricaud/faup#77]
The fragment isn't parsed correctly is the path is implicit.  For example:

$ ./faup -o json "epsg.org#4326"
{
        "scheme": "",
        "credential": "",
        "subdomain": "",
        "domain": "epsg.org#4326",
        "domain_without_tld": "epsg",
        "host": "epsg.org#4326",
        "tld": "org#4326",
        "port": "",
        "resource_path": "",
        "query_string": "",
        "fragment": "",
        "url_type": "unknown_tld"
}

However, if the path is explicit then the fragment is parsed correctly:

$ ./faup -o json "epsg.org/#4326"
{
        "scheme": "",
        "credential": "",
        "subdomain": "",
        "domain": "epsg.org",
        "domain_without_tld": "epsg",
        "host": "epsg.org",
        "tld": "org",
        "port": "",
        "resource_path": "/",
        "query_string": "",
        "fragment": "#4326",
        "url_type": "mozilla_tld"
}

**Comment by stricaud** [comment]
Good catch. Thanks for reporting, very useful to make faup much better!
