### ISSUE TITLE
Fragment parsed incorrectly is multiple # characters

### ISSUE THREAD

**Issue by jdiner** [stricaud/faup#78]
The fragment is parsed incorrectly if it includes a # character.  This causes part of the fragment to be included in the path.  Example:

$ ./faup -o json "http://penlakes.typepad.com/the_personal_blog_of_tom_/#tp_blog_of_tom_/#tp"
{
        "scheme": "http",
        "credential": "",
        "subdomain": "penlakes",
        "domain": "typepad.com",
        "domain_without_tld": "typepad",
        "host": "penlakes.typepad.com",
        "tld": "com",
        "port": "",
        "resource_path": "/the_personal_blog_of_tom_/#tp_blog_of_tom_/",
        "query_string": "",
        "fragment": "#tp",
        "url_type": "mozilla_tld"
}

**Comment by stricaud** [comment]
Thanks for reporting this, I will have a look ASAP
