### ISSUE TITLE
[Feature request] ability to output decimal version of IPv4/IPv6 address

### ISSUE THREAD

**Issue by jksecurity** [stricaud/faup#88]
Hello,

I am using faup to split the record value of DNS records. For cname records (that point to a hostname) this allows me to split the hostname into subdomain, domain and tld. For A/AAAA records (IPv4/IPv6) the DNS record points to an address and faup basically just copies the address into the host field.

After parsing my data I am storing it into a mongodb database. Unfortunately mongo has no native support for IPv4/IPv6 addresses. In order to search for records related to an IP range, I could store the IP addresses as decimal (128 bit 'integer').

I am wondering to what extent faup could help me with this. Within the C++ code hostnames are checked against IPv4 and IPv6 addresses and based on this a certain flag is set. I guess it would be possible to add a conversion here to decimal?

Perhaps a LUA module could be used to overwrite one of the output fields (f.e. the host field) with a decimal version of the IP address if the IPv4/IPv6 flag is set?

**Comment by jksecurity** [comment]
I can probably get it done in LUA with something along these lines:

`function extract_string(orig_url, feature, positions_and_sizes)
	feature_pos=feature .. ".pos"
	feature_size=feature .. ".size"

	if positions_and_sizes[feature_pos] >= 0 
	then 
   	     feature_str = string.sub(orig_url, positions_and_sizes[feature_pos] + 1, positions_and_sizes[feature_pos] + positions_and_sizes[feature_size]) 
	else 
	     feature_str = "" 
	end

	 
	return feature_str
end

function faup_output(orig_url, positions_and_sizes)

	host = extract_string(orig_url, "host", positions_and_sizes)
	subdomain = extract_string(orig_url, "subdomain", positions_and_sizes)
	domain = extract_string(orig_url, "domain", positions_and_sizes)
	tld = extract_string(orig_url, "tld", positions_and_sizes)
	url_type = extract_string(orig_url, "url_type", positions_and_sizes)
	
	if url_type == "ipv4" then
	
		ipdec = 4 -- add calculation here based on host variable
		
	elseif url_type == "ipv6" then
	
		ipdec = 6 -- add calculation here based on host variable
		
	else
		
		ipdec = 0 -- set to 0 if not an ip address
	
	end
	
	io.write(subdomain, "\t", domain, "\t", tld, "\t", ipdec, "\n")
	
	return orig_url, positions_and_sizes
	
end`

**Comment by jksecurity** [comment]
Is it possible that url_type is not available in LUA, due to a missing call in modules.c for this field?

Call similar to:

_faup_add_feature(modules, count, fh->faup.features.fragment, "fragment.pos", "fragment.size");

**Comment by jksecurity** [comment]
After having a closer look at the source code I came to include that url_type is not a feature of a url, which I guess makes sense. As such it is not trivial to expose this to LUA, as the LUA only expects a start and stop value to cut features out of the URL string itself. I will have to reconsider my options, but most likely modifying the c++ code is the way to go here (also for performance).

**Comment by stricaud** [comment]
I am more than happy to include upstream your lua code, and think of a way to get this into the C library. I am reopening so I can see what I can do there. Thanks for the great idea!

**Comment by jksecurity** [comment]
Thank you!!
